name: 'Download Java JDK'
description: 'Download a specific version of the Java JDK'
author: 'Typelevel'
inputs:
  java-version:
    description: 'The Java version to set up. Takes a major Java version'
    required: true
  distribution:
    description: 'Java distribution. See the list of supported distributions in README file'
    required: true
  index:
    description: 'The base url for the JDK index'
    required: false
    default: 'https://raw.githubusercontent.com/typelevel/jdk-index/main/index'
outputs:
  jdkFile:
    description: 'Filename of the downloaded archive.'
    value: ${{ steps.resolve-java.outputs.jdkFile }}
runs:
  using: 'composite'
  steps:
    - id: resolve-java
      shell: bash
      run: |
        JDK_URL=$(curl -L ${{ inputs.index }}/${{ runner.os }}/${{ runner.arch }}/${{ inputs.distribution }}/${{ inputs.java-version }}/jdk)
        JDK_FILE="${{ runner.temp }}/$(basename $JDK_URL)"
        echo "jdkUrl=$JDK_URL" >> $GITHUB_OUTPUT
        echo "jdkFile=$JDK_FILE" >> $GITHUB_OUTPUT
    - id: cache-java
      uses: actions/cache@v3
      with:
        path: ${{ steps.resolve-java.outputs.jdkFile }}
        key: ${{ steps.resolve-java.outputs.jdkUrl }}
    - id: download-java
      if: steps.cache-java.outputs.cache-hit != 'true'
      shell: bash
      working-directory: ${{ runner.temp }}
      run: |
        curl -L -O ${{ steps.resolve-java.outputs.jdkUrl }}
